### ISSUE TITLE
About torch.randperm(gen, n)

### ISSUE THREAD

**Issue by hankobe** [ameenetemady/MyCommon#1]
Hi,
       Excuse me, I am new to lua. And I want to use the function torch.randperm(gen, n) to return a random permutation of integers from 1 to n, but when I input torch.randperm(5,8) , it will appear an error like this:
       expected arguments: [*DoubleTensor*] [Generator] long

      So do you know how it works? 

     Thank you for your reply.

**Comment by ameenetemady** [comment]
Hi, you may see the related documentation [here](https://github.com/torch/torch7/blob/master/doc/maths.md#res-torchrandpermres-gen-n). Basically, you only need to give it a single argument (e.g. torch.randperm(5)), what is "8" that you give it? If you insist to not use the global random generator (default option), then you can do this: torch.randperm(torch.Generator(), 5).  
Note: for this type of question, it's more appropriate to ask on forum (e.g. [this](https://groups.google.com/forum/#!forum/torch7))

**Comment by hankobe** [comment]
Thank you for your immediately reply.
        I mean I want to get a random permutation of integers from 1 to n (e.g. get 3,5,6 from 1,2,3,4,5,6). Can the function torch.randperm(gen, n) do this enough?

**Comment by ameenetemady** [comment]
It seems that you mean "combination", not "permutation", right? if so, for example if you want a random combination of 3 from 6 items, you can simply do:  torch.randperm(6):narrow(1, 1, 3)

**Comment by hankobe** [comment]
Oh, yes. That's the answer I want to find out ^_^. Thank you very much.
By the way, one more question, if I want my "random combination" must have the number 1, what should I simply do next?

**Comment by ameenetemady** [comment]
So, generate one less number of combinations and then append "1" to the list.

**Comment by hankobe** [comment]
That's very kind of you. Thanks!
